/*__author__: "GritFeat Solutions - Nepal"
__copyright__: "Copyright 2022, GritFeat Solutions, Nepal."
__version__: "0.0.1"
__status__: "Dev"
__created_on__: "10/05/2024"
__maintainer__: "Krisha Maharjan"
*/



with cte as(
select 
    "patient_id",
	cast("member_id" as int),
	"active",
	"gender",
	cast("birthdate" as date),
	cast("deceasedboolean" as int),
	cast("deceaseddatetime" as date),
	"maritalstatus_code",
	"race",
	"ethenicity",
	"multiplebirth",
	"contact",
	"communication",
	"generalpractitioner",
	"managingorganization",
	"misc_link",
	"misc_extension",
	"identifier_use",
	"identifier_typecode",
	"identifier_system",
	"identifier_value",
	"identifier_period_start",
	"identifier_period_end",
	"assigner",
	"name_use",
	"name_text",
	"family",
	"given",
	"middlename",
	"prefix",
	"suffix",
	"name_period_start",
	"name_period_end",
	"telecom_system",
	"telecom_value",
	"telecom_use",
	"rank",
	"telecom_period_start",
	"telecom_period_end",
	"address_use",
	"address_type",
	"address_text",
	"line1",
	"line2",
	"line3",
	"line4",
	"city",
	"district",
	"state",
	"postalcode",
	"country",
	"address_period_start",
	"address_period_end",
	"resource_type",
    NULL as "data_source"
from {{ ref("_raw_patient")}}
union
select "patient_id",
	"member_id",
	NULL as "active",
	"gender",
	"birthdate",
	"deceasedboolean",
	"deceaseddatetime",
	NULL as "maritalstatus_code",
	"race",
	NULL as "ethenicity",
	NULL as "multiplebirth",
	NULL as "contact",
	NULL as "communication",
	NULL as "generalpractitioner",
	NULL as "managingorganization",
	NULL as "misc_link",
	NULL as "misc_extension",
	NULL as "identifier_use",
	'patient' as "identifier_typecode",
	'patient' as "identifier_system",
	cast("patient_id" as varchar(50)) as "identifier_value",
	NULL as "identifier_period_start",
	NULL as "identifier_period_end",
	NULL as "assigner",
	NULL as "name_use",
	NULL as "name_text",
	"family",
	"given",
	NULL as "middlename",
	NULL as "prefix",
	NULL as "suffix",
	NULL as "name_period_start",
	NULL as "name_period_end",
	NULL as "telecom_system",
	"telecom_value",
	NULL as "telecom_use",
	NULL as "rank",
	NULL as "telecom_period_start",
	NULL as "telecom_period_end",
	NULL as "address_use",
	NULL as "address_type",
	NULL as "address_text",
	"line1",
	NULL as "line2",
	NULL as "line3",
	NULL as "line4",
	"city",
	NULL as "district",
	"state",
	"postalcode",
	NULL as "country",
	NULL as "address_period_start",
	NULL as "address_period_end",
	NULL as "resource_type",
    "data_source"
 from {{ ref("_raw_eligibility")}}
 union
select "patient_id",
	"member_id",
	NULL as "active",
	"gender",
	"birthdate",
	"deceasedboolean",
	"deceaseddatetime",
	NULL as "maritalstatus_code",
	"race",
	NULL as "ethenicity",
	NULL as "multiplebirth",
	NULL as "contact",
	NULL as "communication",
	NULL as "generalpractitioner",
	NULL as "managingorganization",
	NULL as "misc_link",
	NULL as "misc_extension",
	NULL as "identifier_use",
	'member' as "identifier_typecode",
	'member' as "identifier_system",
	cast("member_id" as varchar(50)) as "identifier_value",
	NULL as "identifier_period_start",
	NULL as "identifier_period_end",
	NULL as "assigner",
	NULL as "name_use",
	NULL as "name_text",
	"family",
	"given",
	NULL as "middlename",
	NULL as "prefix",
	NULL as "suffix",
	NULL as "name_period_start",
	NULL as "name_period_end",
	NULL as "telecom_system",
	"telecom_value",
	NULL as "telecom_use",
	NULL as "rank",
	NULL as "telecom_period_start",
	NULL as "telecom_period_end",
	NULL as "address_use",
	NULL as "address_type",
	NULL as "address_text",
	"line1",
	NULL as "line2",
	NULL as "line3",
	NULL as "line4",
	"city",
	NULL as "district",
	"state",
	"postalcode",
	NULL as "country",
	NULL as "address_period_start",
	NULL as "address_period_end",
	NULL as "resource_type",
    "data_source"
 from {{ ref("_raw_eligibility")}}
)
select * from cte